### ISSUE TITLE
[Octo-Bot/file-transfer-bot] Parser parse only first letter of download/upload file

### ISSUE THREAD

**Issue by slunicko-ondra** [nus-ncl/OctoBot#50]
I tried to run this command: `docker run file-transfer-bot:latest -s <server_ip> -u <ftp_user> -p <ftp_passw
ord> -f download -df test_file`, but I received following error:
```
Download from:
<server_ip>:t
Saving to:
<working_directory>/t
Traceback (most recent call last):
  File "ftp_starter.py", line 46, in <module>
    main()
  File "ftp_starter.py", line 39, in main
    scheduleDownload(args)
  File "/<...>/OctoBot/Octo-Bot/file-transfer-bot/bot/ftp_generator.py", line 37, in scheduleDownload
    jobs.append(Thread(target=doDownload(params),
  File "/<...>/OctoBot/Octo-Bot/file-transfer-bot/bot/ftp_generator.py", line 82, in doDownload
    session.retrbinary(ftpCommand, file.write)
  File "/usr/lib/python3.8/ftplib.py", line 432, in retrbinary
    with self.transfercmd(cmd, rest) as conn:
  File "/usr/lib/python3.8/ftplib.py", line 389, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "/usr/lib/python3.8/ftplib.py", line 355, in ntransfercmd
    resp = self.sendcmd(cmd)
  File "/usr/lib/python3.8/ftplib.py", line 277, in sendcmd
    return self.getresp()
  File "/usr/lib/python3.8/ftplib.py", line 250, in getresp
    raise error_perm(resp)
ftplib.error_perm: 550 t: No such file or directory
```

So the parser reads only the first letter of the filename. It's the same with uploading. I fixed this problem by adding nargs='+' for flags -df and -uf like this:
```
    parser.add_argument("-uf", metavar = 'uploaded_file',
                        help="file to be uploaded",  required=False, nargs='+',
                          default=['/large_file'])
    parser.add_argument("-df", metavar = 'downloaded_file',required=False, nargs='+',
                        help="file to be downloaded",default=['large_file'])
```

It works fine now.

**Comment by slunicko-ondra** [comment]
Note: I think I don't have permission to add labels, so I can't follow contributing guidelines.

**Comment by ariscahyadi** [comment]
Hi @slunicko-ondra ... thank you for the issue report and sorry if you are unable to add labels to it.
But can you make PR for this issue? so that I can merge it.

**Comment by slunicko-ondra** [comment]
Hi @ariscahyadi, the pull request should be ready now.

**Comment by ariscahyadi** [comment]
@slunicko-ondra it is merged. Thank you for your contribution.
